### ISSUE TITLE
Saving my settings doesn't work

### ISSUE THREAD

**Issue by FRBFStudios** [absolllute/Mega-Hack-Pro-Future#1302]
Ever since MH v8 has been updated for 2.206, my mh setting changes of each session, most notably assigned keybinds, are reset when closing the game, even after clicking the top right "save" button. Sometimes a few changes are kept, but I always have to reassign my hotkeys which is extremely annoying. Please consider fixing this issue :(

**Comment by RedWarrior11316** [comment]
That is happening to me as well. Very annoying to deal with.

**Comment by FRBFStudios** [comment]
Nvmd its fixed now

**Comment by RedWarrior11316** [comment]
I just tested again right now and it's still not working for me. Glad that your issue is resolved though. EDIT: Nvm I just realized that it had an update.
